<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> parent of 54c92de (mas)
=======
>>>>>>> parent of 54c92de (mas)
package gui;

import conexion.Conexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARABEY ORELLANA
 */
public class Clientes extends javax.swing.JDialog {
  int longitudBytes;
    File foto;
    FileInputStream entradaFoto;
    ImageIcon icono = new ImageIcon("src/foto.jpg");
    boolean estadoFoto = false;
   
    
   public Clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        int longitudBytes;
       jlbfoto.setIcon(icono);
    }
   String usuario;
    Conexion conect = new Conexion("gimnasio");
    Connection con = null;
    Statement st = null;
    DefaultTableModel modelo;
    Object datosClientes[] = new Object[5];
    String codigo;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtgenero = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        jlbfoto = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        btnleer = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnfoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Genero");

        jLabel5.setText("Peso");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesoActionPerformed(evt);
            }
        });

        jlbfoto.setBackground(new java.awt.Color(0, 153, 153));
        jlbfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbfoto.setText("foto");
        jlbfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtpeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(txtgenero, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jlbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btncrear.setText("Crear");
        btncrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncrearMouseClicked(evt);
            }
        });
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btnleer.setText("Leer");
        btnleer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnleer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnleerMouseClicked(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodificarMouseClicked(evt);
            }
        });
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseClicked(evt);
            }
        });
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir ");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnfoto.setText("Foto");
        btnfoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfotoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FIT GYM");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Genero", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.setGridColor(new java.awt.Color(51, 255, 204));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setResizable(false);
            tblDatos.getColumnModel().getColumn(1).setResizable(false);
            tblDatos.getColumnModel().getColumn(2).setResizable(false);
            tblDatos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DATOS DEL CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnleer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnleer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void crearCliente() {
       
        if(txtnombre.getText().isEmpty()||txtedad.getText().isEmpty()||txtgenero.getText().isEmpty()||txtpeso.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PORFAVOR ASEGURESE DE QUE TODOS LOS CAMPOS ESTEN LLENOS", "ATENCION!", 1);
       }else{
           try {
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
       
            String sql = "INSERT INTO clientes (ID,Nombre,Edad,Genero,Peso,Foto,Estado) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement ps = conect.getConexion().prepareStatement(sql);
          
            ps.setInt(1, 0);
            ps.setString(2, txtnombre.getText());
            ps.setString(3, txtedad.getText());
            ps.setString(4, txtgenero.getText());
            ps.setString(5, txtpeso.getText());
            ps.setBlob(6, entradaFoto, longitudBytes);
            ps.setString(7, "Activo"); 
            ps.execute();
            con.close();
            JOptionPane.showMessageDialog(null, "EL REGISTRO SE HA CREADO", "ATENCION!", JOptionPane.INFORMATION_MESSAGE);
            limpiarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ATENCION!" + e, 0);
        }  
       }     //To change body of generated methods, choose Tools | Templates.
    }
    private void actualizarCliente() {
        
        try {

                Conexion conect = new Conexion("gimnasio");
                con = conect.getConexion();
                st = con.createStatement();
                PreparedStatement ps;

                String sql = "UPDATE clientes SET Nombre=?, Edad=?,Genero=? ,Peso=?,foto=? WHERE ID =? AND Estado = 'Activo'";
                ps = conect.getConexion().prepareStatement(sql);
                ps.setString(1,txtnombre.getText());
                ps.setString(2, txtedad.getText());
                ps.setString(3, txtgenero.getText());
                ps.setString(4, txtpeso.getText());
                ps.setBlob(5, entradaFoto, longitudBytes);
                 ps.setString(6,codigo);
                ps.execute();
                JOptionPane.showMessageDialog(null, "SU REGISTRO SE A ACTUALIZADO CORRECTAMENTE", "ATENCION!", 1);
                limpiarTabla();
                con.close();                
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "SU REGISTRO NO SE A PODIDO ACTUALIZAR" + e, "ATENCION!", 0);
            } 
    }        
        //METODO PARA SELECCIONAR LA FOTO
     public void seleccionarFoto() {
        //Nos permite a través de una ventana, seleccioar un archivo
        JFileChooser seleccionarFoto = new JFileChooser();
        FileNameExtensionFilter filtro;// seleccionamos el tipo de extensión de la imagen
        filtro = new FileNameExtensionFilter("JPG, PNG, GIF", "jpg", "png", "gif");
        seleccionarFoto.setFileFilter(filtro);
        //colocamos un titulo a la ventana (opcional)
        seleccionarFoto.setDialogTitle("BUSCAR FOTO");
        //Establecemos una ruta con la carpeta de las imagenes (opcional)
        File ruta = new File("C:/foto");
        seleccionarFoto.setCurrentDirectory(ruta);
        int estado = seleccionarFoto.showOpenDialog(this);
        //Si el usuario dio click en botón aceptar
        if (estado == JFileChooser.APPROVE_OPTION) {
            try {
                //seleccionamos la foto
                entradaFoto = new FileInputStream(seleccionarFoto.getSelectedFile());
                //tomamos la medida de la imagen en bytes
                this.longitudBytes = (int) seleccionarFoto.getSelectedFile().length();
                //tomamos el tamaño de la etiqueta y colocamos la imagen en ella 
                Image iconoF = ImageIO.read(seleccionarFoto.getSelectedFile()).getScaledInstance(jlbfoto.getWidth(), jlbfoto.getHeight(), Image.SCALE_DEFAULT);
                jlbfoto.setIcon(new ImageIcon(iconoF));
                //variable bandera que la utilizamoa al momento de actualizar
                estadoFoto = true;

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex, "ATENCION!", 0);
            } catch (IOException exp) {
                JOptionPane.showMessageDialog(null, exp, "ATENCION!", 0);
            }
        }
     }
     
        
     private void BuscarFoto(String cod) {

        try {
            String encontrado = "NO";
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM clientes WHERE ID =" + cod);
            ImageIcon iconoBD;
            InputStream salidaFoto;
            Image imageBD;
            Image nuevaImgModificada;
            while (rs.next()) {
                salidaFoto = rs.getBinaryStream("foto"); //Saco la foto de la BD
                BufferedImage im = ImageIO.read(salidaFoto);
                iconoBD = new ImageIcon(im);
                imageBD = iconoBD.getImage();
                nuevaImgModificada = imageBD.getScaledInstance(jlbfoto.getWidth(), jlbfoto.getHeight(), Image.SCALE_DEFAULT);//Utilice el algoritmo de escalado de imágenes predeterminado.
                //nuevaImgModificada = imageBD.getScaledInstance(170, 170, Image.SCALE_SMOOTH);//Elija un algoritmo de escalado de imagen que dé mayor prioridad a la suavidad de la imagen que a la velocidad de escalado.
                ImageIcon mostrarFoto = new ImageIcon(nuevaImgModificada);
                jlbfoto.setIcon(mostrarFoto);
                encontrado = "SI";
            }
            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "ID DE CLIENTE NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
        } catch (HeadlessException | IOException | SQLException y) {
        }
     
     
    }
     private void BuscarCliente() {
         try {
            Conexion conect = new Conexion("gimnasio");
            String senten = "SELECT * FROM clientes WHERE Estado LIKE 'activo' AND Nombre LIKE '"+txtnombre.getText()+"%'";
            String encontrado = "no";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);
            modelo = (DefaultTableModel) tblDatos.getModel();

            while (rs.next()) {
                datosClientes[0] = (rs.getString("ID"));
                datosClientes[1] = (rs.getString("Nombre"));
                datosClientes[2] = (rs.getString("Edad"));
                datosClientes[3] = (rs.getString("Genero"));
                datosClientes[4] = (rs.getString("Peso"));
                modelo.addRow(datosClientes);
                encontrado = "SI";
            }

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "REGISTRO NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            tblDatos.setModel(modelo);
            con.close();
        } catch (HeadlessException | SQLException x) {} //To change body of generated methods, choose Tools | Templates.
    }
private void limpiarTabla() {
        try {
        int fila = tblDatos.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        limpiar();
    } catch (Exception e) {
    }
 //To change body of generated methods, choose Tools | Templates.
    }
public void limpiar(){
        txtnombre.setText("");
        txtedad.setText("");
        txtgenero.setText("");
        txtpeso.setText("");
    }

 private void eliminarCliente() {
        try {
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            st = con.createStatement();
            PreparedStatement ps;
            
            String elimina = "UPDATE clientes SET Estado=? WHERE ID =? AND Estado = 'Activo'";
            String estado = "Inactivo";
            ps = conect.getConexion().prepareStatement(elimina);
            ps.setString(1,estado);
            ps.setString(2,codigo);
            ps.execute();
            JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO CORRECTAMENTE", "ATENCION!", 1);
            con.close();
            limpiarTabla();
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR EL REGISTRO", "ATENCION!", 0);
        } //To change body of generated methods, choose Tools | Templates.
    }
    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
      
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       
    }//GEN-LAST:event_btnmodificarActionPerformed


    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
this.dispose();              // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearMouseClicked
       crearCliente(); // TODO add your handling code here:
    }//GEN-LAST:event_btncrearMouseClicked

    private void btnmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseClicked
        actualizarCliente();// TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarMouseClicked

    private void btnleerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnleerMouseClicked
       BuscarCliente(); // TODO add your handling code here:
    }//GEN-LAST:event_btnleerMouseClicked

    private void btnlimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseClicked
      limpiarTabla();  // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
       eliminarCliente();// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
int fila = tblDatos.getSelectedRow();
        txtnombre.setText(tblDatos.getValueAt(fila, 0).toString());
        txtedad.setText(tblDatos.getValueAt(fila, 1).toString());
        txtgenero.setText(tblDatos.getValueAt(fila, 2).toString());
        txtpeso.setText(tblDatos.getValueAt(fila, 3).toString());
        BuscarFoto(codigo.trim());
             // TODO add your handling code here:
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfotoActionPerformed
      seleccionarFoto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnfotoActionPerformed
 public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Clientes dialog = new Clientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnfoto;
    private javax.swing.JButton btnleer;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbfoto;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables

   

}
        


    

<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> parent of f7c7ab7 ()
package gui;

import conexion.Conexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARABEY ORELLANA
 */
public class Clientes extends javax.swing.JDialog {
  int longitudBytes;
    File foto;
    FileInputStream entradaFoto;
    ImageIcon icono = new ImageIcon("src/foto.jpg");
    boolean estadoFoto = false;
   
    
   public Clientes(java.awt.Frame parent, boolean modal,String user) {
        super(parent, modal);
        initComponents();
        int longitudBytes;
       jlbfoto.setIcon(icono);
    }
   Connection con = null;
    Statement st = null;
    String encontrado;
   String usuario;
    Conexion conect = new Conexion("gimnasio");
    
    DefaultTableModel modelo;
    Object datosClientes[] = new Object[5];
    String codigo;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtgenero = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        jlbfoto = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        btnleer = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnfoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Genero");

        jLabel5.setText("Peso");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesoActionPerformed(evt);
            }
        });

        jlbfoto.setBackground(new java.awt.Color(0, 153, 153));
        jlbfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbfoto.setText("foto");
        jlbfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtpeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(txtgenero, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jlbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btncrear.setText("Crear");
        btncrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncrearMouseClicked(evt);
            }
        });
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btnleer.setText("Leer");
        btnleer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnleer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnleerMouseClicked(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodificarMouseClicked(evt);
            }
        });
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlimpiarMouseClicked(evt);
            }
        });
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir ");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnfoto.setText("Foto");
        btnfoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfotoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FIT GYM");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
<<<<<<< HEAD
                "ID", "Nombre", "Edad", "Genero", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
=======
                "Nombre", "Edad", "Genero", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
>>>>>>> parent of f7c7ab7 ()
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.setGridColor(new java.awt.Color(51, 255, 204));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setResizable(false);
            tblDatos.getColumnModel().getColumn(1).setResizable(false);
            tblDatos.getColumnModel().getColumn(2).setResizable(false);
            tblDatos.getColumnModel().getColumn(3).setResizable(false);
<<<<<<< HEAD
            tblDatos.getColumnModel().getColumn(4).setResizable(false);
=======
>>>>>>> parent of f7c7ab7 ()
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DATOS DEL CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnleer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
<<<<<<< HEAD
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addContainerGap(0, Short.MAX_VALUE))
>>>>>>> parent of f7c7ab7 ()
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnleer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void crearCliente() {
       
        if(txtnombre.getText().isEmpty()||txtedad.getText().isEmpty()||txtgenero.getText().isEmpty()||txtpeso.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "PORFAVOR ASEGURESE DE QUE TODOS LOS CAMPOS ESTEN LLENOS", "ATENCION!", 1);
       }else{
           try {
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
       
            String sql = "INSERT INTO clientes (ID,Nombre,Edad,Genero,Peso,Foto,Estado) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement ps = conect.getConexion().prepareStatement(sql);
          
            ps.setInt(1, 0);
            ps.setString(2, txtnombre.getText());
            ps.setString(3, txtedad.getText());
            ps.setString(4, txtgenero.getText());
            ps.setString(5, txtpeso.getText());
            ps.setBlob(6, entradaFoto, longitudBytes);
            ps.setString(7, "Activo"); 
            ps.execute();
            con.close();
            JOptionPane.showMessageDialog(null, "EL REGISTRO SE HA CREADO", "ATENCION!", JOptionPane.INFORMATION_MESSAGE);
            limpiarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ATENCION!" + e, 0);
        }  
       }     //To change body of generated methods, choose Tools | Templates.
    }
    private void actualizarCliente() {
        
        try {

                Conexion conect = new Conexion("gimnasio");
                con = conect.getConexion();
                st = con.createStatement();
                PreparedStatement ps;

<<<<<<< HEAD
                String sql = "UPDATE clientes SET Nombre=?, Edad=?,Genero=? ,Peso=? WHERE ID =? AND Estado = 'Activo'";
=======
                String sql = "UPDATE clientes SET Nombre=?, Edad=?,Genero=? ,Peso=?,foto=? WHERE ID =? AND Estado = 'Activo'";
>>>>>>> parent of f7c7ab7 ()
                ps = conect.getConexion().prepareStatement(sql);
                ps.setString(1,txtnombre.getText());
                ps.setString(2, txtedad.getText());
                ps.setString(3, txtgenero.getText());
                ps.setString(4, txtpeso.getText());
<<<<<<< HEAD
                //ps.setBlob(5, entradaFoto, longitudBytes);
                 ps.setString(5,codigo);
=======
                ps.setBlob(5, entradaFoto, longitudBytes);
                 ps.setString(6,codigo);
>>>>>>> parent of f7c7ab7 ()
                ps.execute();
                JOptionPane.showMessageDialog(null, "SU REGISTRO SE A ACTUALIZADO CORRECTAMENTE", "ATENCION!", 1);
                limpiarTabla();
                con.close();                
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "SU REGISTRO NO SE A PODIDO ACTUALIZAR" + e, "ATENCION!", 0);
            } 
    }        
<<<<<<< HEAD
        
=======
        //METODO PARA SELECCIONAR LA FOTO
     public void seleccionarFoto() {
        //Nos permite a través de una ventana, seleccioar un archivo
        JFileChooser seleccionarFoto = new JFileChooser();
        FileNameExtensionFilter filtro;// seleccionamos el tipo de extensión de la imagen
        filtro = new FileNameExtensionFilter("JPG, PNG, GIF", "jpg", "png", "gif");
        seleccionarFoto.setFileFilter(filtro);
        //colocamos un titulo a la ventana (opcional)
        seleccionarFoto.setDialogTitle("BUSCAR FOTO");
        //Establecemos una ruta con la carpeta de las imagenes (opcional)
        File ruta = new File("C:/foto");
        seleccionarFoto.setCurrentDirectory(ruta);
        int estado = seleccionarFoto.showOpenDialog(this);
        //Si el usuario dio click en botón aceptar
        if (estado == JFileChooser.APPROVE_OPTION) {
            try {
                //seleccionamos la foto
                entradaFoto = new FileInputStream(seleccionarFoto.getSelectedFile());
                //tomamos la medida de la imagen en bytes
                this.longitudBytes = (int) seleccionarFoto.getSelectedFile().length();
                //tomamos el tamaño de la etiqueta y colocamos la imagen en ella 
                Image iconoF = ImageIO.read(seleccionarFoto.getSelectedFile()).getScaledInstance(jlbfoto.getWidth(), jlbfoto.getHeight(), Image.SCALE_DEFAULT);
                jlbfoto.setIcon(new ImageIcon(iconoF));
                //variable bandera que la utilizamoa al momento de actualizar
                estadoFoto = true;

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex, "ATENCION!", 0);
            } catch (IOException exp) {
                JOptionPane.showMessageDialog(null, exp, "ATENCION!", 0);
            }
        }
     }
>>>>>>> parent of f7c7ab7 ()
     
        
     private void BuscarFoto(String cod) {

        try {
            String encontrado = "NO";
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM clientes WHERE ID =" + cod);
            ImageIcon iconoBD;
            InputStream salidaFoto;
            Image imageBD;
            Image nuevaImgModificada;
            while (rs.next()) {
                salidaFoto = rs.getBinaryStream("foto"); //Saco la foto de la BD
                BufferedImage im = ImageIO.read(salidaFoto);
                iconoBD = new ImageIcon(im);
                imageBD = iconoBD.getImage();
                nuevaImgModificada = imageBD.getScaledInstance(jlbfoto.getWidth(), jlbfoto.getHeight(), Image.SCALE_DEFAULT);//Utilice el algoritmo de escalado de imágenes predeterminado.
<<<<<<< HEAD
                nuevaImgModificada = imageBD.getScaledInstance(170, 170, Image.SCALE_SMOOTH);//Elija un algoritmo de escalado de imagen que dé mayor prioridad a la suavidad de la imagen que a la velocidad de escalado.
=======
                //nuevaImgModificada = imageBD.getScaledInstance(170, 170, Image.SCALE_SMOOTH);//Elija un algoritmo de escalado de imagen que dé mayor prioridad a la suavidad de la imagen que a la velocidad de escalado.
>>>>>>> parent of f7c7ab7 ()
                ImageIcon mostrarFoto = new ImageIcon(nuevaImgModificada);
                jlbfoto.setIcon(mostrarFoto);
                encontrado = "SI";
            }
            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "ID DE CLIENTE NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
<<<<<<< HEAD
        } catch (HeadlessException | IOException | SQLException y) {System.out.println(y);
=======
        } catch (HeadlessException | IOException | SQLException y) {
>>>>>>> parent of f7c7ab7 ()
        }
     
     
    }
     private void BuscarCliente() {
         try {
            Conexion conect = new Conexion("gimnasio");
            String senten = "SELECT * FROM clientes WHERE Estado LIKE 'activo' AND Nombre LIKE '"+txtnombre.getText()+"%'";
            String encontrado = "no";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);
            modelo = (DefaultTableModel) tblDatos.getModel();

            while (rs.next()) {
                datosClientes[0] = (rs.getString("ID"));
                datosClientes[1] = (rs.getString("Nombre"));
                datosClientes[2] = (rs.getString("Edad"));
                datosClientes[3] = (rs.getString("Genero"));
                datosClientes[4] = (rs.getString("Peso"));
                modelo.addRow(datosClientes);
                encontrado = "SI";
            }

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "REGISTRO NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            tblDatos.setModel(modelo);
            con.close();
        } catch (HeadlessException | SQLException x) {} //To change body of generated methods, choose Tools | Templates.
    }
private void limpiarTabla() {
        try {
        int fila = tblDatos.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        limpiar();
    } catch (Exception e) {
    }
 //To change body of generated methods, choose Tools | Templates.
    }
public void limpiar(){
        txtnombre.setText("");
        txtedad.setText("");
        txtgenero.setText("");
        txtpeso.setText("");
    }

 private void eliminarCliente() {
        try {
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            st = con.createStatement();
            PreparedStatement ps;
            
            String elimina = "UPDATE clientes SET Estado=? WHERE ID =? AND Estado = 'Activo'";
            String estado = "Inactivo";
            ps = conect.getConexion().prepareStatement(elimina);
            ps.setString(1,estado);
            ps.setString(2,codigo);
            ps.execute();
            JOptionPane.showMessageDialog(null, "REGISTRO ELIMINADO CORRECTAMENTE", "ATENCION!", 1);
            con.close();
            limpiarTabla();
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR EL REGISTRO", "ATENCION!", 0);
        } //To change body of generated methods, choose Tools | Templates.
    }
    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
      
    }//GEN-LAST:event_btncrearActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       
    }//GEN-LAST:event_btnmodificarActionPerformed


    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
this.dispose();              // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrearMouseClicked
       crearCliente(); 
       new tomarfoto2(this, true, String.valueOf(BuscarMaxCod())).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btncrearMouseClicked

    private void btnmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseClicked
<<<<<<< HEAD
        actualizarCliente();
        new tomarfoto2(this, true, String.valueOf(codigo)).setVisible(true);
=======
        actualizarCliente();// TODO add your handling code here:
>>>>>>> parent of f7c7ab7 ()
    }//GEN-LAST:event_btnmodificarMouseClicked

    private void btnleerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnleerMouseClicked
       BuscarCliente(); // TODO add your handling code here:
    }//GEN-LAST:event_btnleerMouseClicked

    private void btnlimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlimpiarMouseClicked
      limpiarTabla();  // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
       eliminarCliente();// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
<<<<<<< HEAD
        try {
         int fila = tblDatos.getSelectedRow();
         codigo = tblDatos.getValueAt(fila, 0).toString();
        txtnombre.setText(tblDatos.getValueAt(fila, 1).toString());
        txtedad.setText(tblDatos.getValueAt(fila, 2).toString());
        txtgenero.setText(tblDatos.getValueAt(fila, 3).toString());
        txtpeso.setText(tblDatos.getValueAt(fila, 4).toString());
        
       BuscarFoto(codigo.trim());   
        } catch (Exception e) {
        }
        
=======
int fila = tblDatos.getSelectedRow();
        txtnombre.setText(tblDatos.getValueAt(fila, 0).toString());
        txtedad.setText(tblDatos.getValueAt(fila, 1).toString());
        txtgenero.setText(tblDatos.getValueAt(fila, 2).toString());
        txtpeso.setText(tblDatos.getValueAt(fila, 3).toString());
        BuscarFoto(codigo.trim());
>>>>>>> parent of f7c7ab7 ()
             // TODO add your handling code here:
    }//GEN-LAST:event_tblDatosMouseClicked

   private int BuscarMaxCod() {
        Conexion conect = new Conexion("gimnasio");
        int maximo = 0;
        try {           
            String senten = "SELECT MAX(ID) FROM clientes";
            encontrado = "NO";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);         
            rs.next();
                maximo = rs.getInt("MAX(ID)");
                encontrado = "SI";         
            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
        } catch (HeadlessException | SQLException x) {System.out.println(x);}
        return maximo;
    } 
    
    private void btnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfotoActionPerformed
<<<<<<< HEAD
if(codigo != null){
new tomarfoto2(this, true, codigo).setVisible(true); 
}
            // seleccionarFoto();        // TODO add your handling code here:
=======
      seleccionarFoto();        // TODO add your handling code here:
>>>>>>> parent of f7c7ab7 ()
    }//GEN-LAST:event_btnfotoActionPerformed
 public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Clientes dialog = new Clientes(new javax.swing.JFrame(), true,"user");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnfoto;
    private javax.swing.JButton btnleer;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbfoto;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables

   

}
        


    

<<<<<<< HEAD
>>>>>>> f7c7ab7855affc689f8df4902e743b05856e76ca
=======
>>>>>>> parent of f7c7ab7 ()
=======
>>>>>>> parent of 54c92de (mas)
=======
>>>>>>> parent of 54c92de (mas)
