/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexion.Conexion;
import java.awt.HeadlessException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author lenin
 */
public class frmActPeso extends javax.swing.JDialog {

    Conexion conect;
    Object datosCliente[] = new Object[5];
    Connection con = null;
    Statement st = null;
    Statement st2 = null;
    public frmActPeso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(502, 556);
        setLocationRelativeTo(null);
        DatosClientes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPeso = new javax.swing.JTextField();
        btnGrafica = new javax.swing.JButton();
        cboNombre = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtIdMembresia = new javax.swing.JTextField();
        txtIdNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        txtPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPeso);
        txtPeso.setBounds(150, 244, 210, 50);

        btnGrafica.setText("<html><center>Mostrar grafica</center></html>");
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrafica);
        btnGrafica.setBounds(90, 380, 330, 60);

        cboNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombreActionPerformed(evt);
            }
        });
        getContentPane().add(cboNombre);
        cboNombre.setBounds(150, 140, 210, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizacion de peso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 50, 220, 60);
        getContentPane().add(txtIdMembresia);
        txtIdMembresia.setBounds(230, 320, 90, 40);
        getContentPane().add(txtIdNombre);
        txtIdNombre.setBounds(110, 320, 90, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Escriba su peso actual");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(161, 206, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombreActionPerformed
        // TODO add your handling code here:
        BuscarNombreCliente();
    }//GEN-LAST:event_cboNombreActionPerformed

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        // TODO add your handling code here:
        //IngresarPeso();
        reportePorNombre();
    }//GEN-LAST:event_btnGraficaActionPerformed

    public void DatosClientes() {
        try {
            
            conect = new Conexion("gimnasio");
            String senten = "SELECT `nombre` FROM `clientes`";
            String encontrado = "NO";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);

            while (rs.next()) {
                cboNombre.addItem(rs.getString("nombre"));
                encontrado = "SI";
            }
            BuscarNombreCliente();
                
            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
        } catch (HeadlessException | SQLException x) {
            System.out.println(x);
        }
    } 
    private void BuscarNombreCliente() {        
            try {
                
                conect = new Conexion("gimnasio");
                String senten = "SELECT ID FROM `clientes` WHERE `nombre` LIKE '"+cboNombre.getSelectedItem().toString()+"'";
                String encontrado = "NO";            
                con = conect.getConexion();
                st = con.createStatement();
                ResultSet rs = st.executeQuery(senten);

                while (rs.next()) {
                    txtIdNombre.setText(rs.getString("ID"));
                    encontrado = "SI";
                }
                if (encontrado.equals("NO")) {
                    JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
                }
                con.close();
            } catch (HeadlessException | SQLException x) {
                System.out.println(""+x.getMessage());
            }
           
    }
    public void IngresarPeso(){
        if (txtPeso.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Error, debe de llenar el campo", "", JOptionPane.WARNING_MESSAGE);
        }
        try {
            
                conect = new Conexion("gimnasio");
                con = conect.getConexion();
                //COLOQUE EN LA SENTENCIA SQL EL NOMBRE DE SU BD Y LOS NOMBRE DE LOS CAMPOS
                String sql = "INSERT INTO actualizacion_peso (ID, IDcliente, pesoActual) VALUES (?,?,?)";
                PreparedStatement ps = conect.getConexion().prepareStatement(sql);
                //COLOQUE LOS NOMBRES DE SUS CUADROS DE DIALOGO (JTEXTFIELD)
                   ps.setInt(1, 0);                
                ps.setInt(2, Integer.parseInt(txtIdNombre.getText()));
                ps.setInt(3, Integer.parseInt(txtPeso.getText()));   
                ps.execute();
                JOptionPane.showMessageDialog(null, "SE A INGRESADO CORRECTAMENTE", "ATENCION!", 1);
                
                con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "REGISTRO NO SE PUDO GUARDAR "+ e.getMessage(), "ATENCION!", 0);
            }
    }
    public void reporteVe_CliIreport(){
    try{
             Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            
            JasperReport repor=null;
            URL urlMaestro = getClass().getResource("src/gui/EvolucionDePeso.jasper");            
            repor=(JasperReport) JRLoader.loadObject(urlMaestro);
            
            JasperPrint jprint = JasperFillManager.fillReport(repor,null, con);
            
            JasperViewer view = new JasperViewer(jprint,true);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
        
        }catch (JRException e){System.out.print(e);}     
    }
    public void reportePorNombre() {
        //Obtenemos el nombre que lo mandaremos por parámetro al reporte para la búsqueda
        //String nombre = JOptionPane.showInputDialog("INGRESE EL NOMBRE A BUSCAR");
        Conexion conect = new Conexion("gimnasio");
        con = conect.getConexion();
        try {

            Map parametro = new HashMap();//Variable donde mandamos los parámetros a iReport
            parametro.put("Nombre", cboNombre.getSelectedItem().toString());//Colocamos e nombre del parametro que creamos en iReport que será la
                                         //que reciba el parámetro que mandamos desde la aplicaión, y tambien 
                                         //colocamos el nombre del parámetro que enviamos desde la aplicación
           
            //parametro.put("color", color); Si necesitamos enviar otros parámetros usamos la misma variable de tipo Map
            JasperReport reporte = null;

             //RUTA DEL ARCHIVO
            URL urlMaestro = getClass().getResource("/gui/EvolucionDePeso.jasper");
            //LLAMADO DEL ARCHIVO
            reporte = (JasperReport) JRLoader.loadObject(urlMaestro);
            //LLENADO DEL REPORTE
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, con);
            //VISTA DEL REPORTE
            JasperViewer view = new JasperViewer(jprint, false);
            //TITULO (OPCIONAL)
//            view.setTitle("REPORTE DE CLIENTES");
            //CIERRE DEL REPORTE
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e.getMessage());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActPeso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmActPeso dialog = new frmActPeso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafica;
    private javax.swing.JComboBox<String> cboNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtIdMembresia;
    private javax.swing.JTextField txtIdNombre;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
