package gui;

import conexion.Conexion;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    Conexion conect;
    Connection con = null;
    Statement st = null;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    String encontrado;

    private void BuscarUser() {
         conect = new Conexion("gimnasio");
        if (jtfUser.getText().equals("") || jpfPass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error\ncampos Vacios.", null, JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String senten = "SELECT * FROM usuarios WHERE user LIKE '"+jtfUser.getText() +"'";
                encontrado = "NO";
                con = conect.getConexion();
                st = con.createStatement();
                ResultSet rs = st.executeQuery(senten);

                while (rs.next()) {
                        if (jpfPass.getText().equals(rs.getString("pass"))) {

                            JOptionPane.showMessageDialog(null, "Bienvenido " + jtfUser.getText());
                            this.dispose();
                            new Principal(jtfUser.getText()).setVisible(true);
                            encontrado = "SI";
                           
                        } else {
                            JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                        }
                    
                    encontrado = "SI";
                    limpiar();
                }
                if (encontrado.equals("NO")) {
                    JOptionPane.showMessageDialog(null, "USUARIO INCORRECTO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
                }

                con.close();
            } catch (HeadlessException | SQLException x) {
                System.out.println(x);
            }
        }
    }
    
    private void limpiar(){
        jtfUser.setText("");
        jpfPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jpfPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        botSalir = new javax.swing.JButton();
        botIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PASSWORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 220, 110, 20);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel2.setText("FIT GYM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 40, 140, 30);
        jPanel1.add(jtfUser);
        jtfUser.setBounds(90, 160, 130, 40);
        jPanel1.add(jpfPass);
        jpfPass.setBounds(90, 260, 130, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("USUARIO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 120, 90, 20);

        botSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botSalir.setText("SALIR");
        botSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 6, true));
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botSalir);
        botSalir.setBounds(310, 230, 120, 50);

        botIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botIngresar.setText("INGRESAR");
        botIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 6, true));
        botIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(botIngresar);
        botIngresar.setBounds(310, 150, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botIngresarActionPerformed
        BuscarUser();
    }//GEN-LAST:event_botIngresarActionPerformed

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login



.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login



.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login



.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login



.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botIngresar;
    private javax.swing.JButton botSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfPass;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
}
