/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import conexion.Conexion;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
/**
 *
 * @author RAY
 */
public class Pagos extends javax.swing.JDialog {

    /**
     * Creates new form Pagos
     */
    public Pagos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BuscarCliente();
    }
    
    DefaultTableModel modelo;
Object datosCliente[] = new Object[3];
String encontrado;

Conexion conect = new Conexion("gimnasio");
Connection con = null;
Statement st = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(892, 606));
        setMinimumSize(new java.awt.Dimension(892, 606));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(892, 606));
        jPanel1.setMinimumSize(new java.awt.Dimension(892, 606));
        jPanel1.setLayout(null);

        jtblDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Genero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblDatos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(232, 330, 636, 270);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tipo de Pago"));
        jPanel2.setLayout(null);

        jRadioButton1.setText("Diaria");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(25, 45, 53, 23);

        jRadioButton2.setText("Semanal");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(25, 97, 65, 23);

        jRadioButton3.setText("Mensual");
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(25, 202, 65, 23);

        jRadioButton4.setText("Quincenal");
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(25, 152, 73, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 330, 200, 270);

        jButton1.setText("Volver");
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 250, 120, 50);

        jButton2.setText("Pagar");
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 250, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 892, 606);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void BuscarCliente() {
        try {
            String senten = "SELECT * FROM clientes WHERE estado LIKE 'Activo'";
            encontrado = "NO";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);
            modelo = (DefaultTableModel) jtblDatos.getModel(); //tblDatos es el nombre del JTable

            while (rs.next()) {
                datosCliente[0] = (rs.getInt("id"));
                datosCliente[1] = (rs.getString("nombre"));
                datosCliente[2] = (rs.getString("genero"));
                
                modelo.addRow(datosCliente);
                encontrado = "SI";
                //limpiar();
            }

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            jtblDatos.setModel(modelo);
            con.close();
        } catch (HeadlessException | SQLException x) {System.out.println(x);}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pagos dialog = new Pagos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblDatos;
    // End of variables declaration//GEN-END:variables
}
