
package gui;

import GUI.Membresias;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal(String usuario) {
        initComponents();
        this.usuario=usuario;
    }
    String usuario;

    private Principal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botClientes = new javax.swing.JButton();
        botSalir = new javax.swing.JButton();
        botMembresias = new javax.swing.JButton();
        botPagos = new javax.swing.JButton();
        botPesoActual = new javax.swing.JButton();
        botVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel2.setLayout(null);

        botClientes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botClientes.setText("CLIENTES");
        botClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        botClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botClientesActionPerformed(evt);
            }
        });
        jPanel2.add(botClientes);
        botClientes.setBounds(20, 40, 110, 50);

        botSalir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botSalir.setText("SALIR");
        botSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });
        jPanel2.add(botSalir);
        botSalir.setBounds(370, 230, 110, 50);

        botMembresias.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botMembresias.setText("MEMBRESIAS");
        botMembresias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        botMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMembresiasActionPerformed(evt);
            }
        });
        jPanel2.add(botMembresias);
        botMembresias.setBounds(20, 140, 110, 50);

        botPagos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botPagos.setText("PAGOS");
        botPagos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        botPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPagosActionPerformed(evt);
            }
        });
        jPanel2.add(botPagos);
        botPagos.setBounds(20, 230, 110, 50);

        botPesoActual.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botPesoActual.setText("REPORTES");
        botPesoActual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        botPesoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesoActualActionPerformed(evt);
            }
        });
        jPanel2.add(botPesoActual);
        botPesoActual.setBounds(370, 40, 110, 50);

        botVolver.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        botVolver.setText("VOLVER");
        botVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 4, true));
        botVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVolverActionPerformed(evt);
            }
        });
        jPanel2.add(botVolver);
        botVolver.setBounds(370, 130, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("PRINCIPAL");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 140, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("MENU");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(220, 100, 70, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSalirActionPerformed

    private void botClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botClientesActionPerformed
        new Cliente(this,true).setVisible(true);
    }//GEN-LAST:event_botClientesActionPerformed

    private void botMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMembresiasActionPerformed
        new Membresias(this,true).setVisible(true);
    }//GEN-LAST:event_botMembresiasActionPerformed

    private void botPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPagosActionPerformed
        new Pagos(this,true).setVisible(true);
    }//GEN-LAST:event_botPagosActionPerformed

    private void botPesoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesoActualActionPerformed
        //new frmActPeso(this,true).setVisible(true);
    }//GEN-LAST:event_botPesoActualActionPerformed

    private void botVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botClientes;
    private javax.swing.JButton botMembresias;
    private javax.swing.JButton botPagos;
    private javax.swing.JButton botPesoActual;
    private javax.swing.JButton botSalir;
    private javax.swing.JButton botVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
