/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexion.Conexion;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RAY
 */
public class tomarfoto2 extends javax.swing.JDialog {

    /**
     * Creates new form tomarfoto2
     */
    public tomarfoto2(javax.swing.JDialog parent, boolean modal , String codigo) {
        super(parent, modal);
        initComponents();
        cod = codigo;
    }
Connection con = null;
    Statement st = null;
    String encontrado;
String cod;
    private tomarfoto2(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void maximoid(){
    
        
    }
    
    public void guardarFoto(Connection con) {
    
        byte imagen[] = jpfoto.getBytes();
        String sentencia = "UPDATE clientes SET foto=? WHERE ID = "+cod;
        try {

            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            PreparedStatement ps = con.prepareStatement(sentencia);
            System.out.println(cod);
            ps.setBytes(1, imagen);
            ps.execute();
            JOptionPane.showMessageDialog(null, "FOTO INGRESADA CORRECTAMENTE");
           // limpiar();
            con.close();

        } catch (SQLException e) {System.out.println(e);
            JOptionPane.showMessageDialog(null, "REGISTRO NO SE PUDO GUARDAR", "ATENCION!", 0);
        }
    }
    byte [] imagen;
public byte[] verFoto(Connection con) {
        //String cod = JOptionPane.showInputDialog("INGRESE EL CODIGO A BUSCAR");
        try {
            String encontrado = "NO";
            Conexion conect = new Conexion("gimnasio");
            con = conect.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT foto FROM clientes WHERE ID=" + cod);

            rs.next();

             imagen = rs.getBytes("foto");
            //jpfoto.setImagen(imagen);//SE COLOCA EN EL PANEL
            encontrado = "SI";

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "ID DE CLIENTE NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();

        } catch (HeadlessException | SQLException y) {}
        return imagen;
}
    
//    private tomarfoto() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnguardarfoto = new javax.swing.JButton();
        btnverfoto = new javax.swing.JButton();
        jpfoto = new JPanelWebCam.JPanelWebCam();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(788, 603));
        setMinimumSize(new java.awt.Dimension(788, 603));
        setPreferredSize(new java.awt.Dimension(788, 603));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(788, 603));
        jPanel1.setMinimumSize(new java.awt.Dimension(788, 603));
        jPanel1.setPreferredSize(new java.awt.Dimension(788, 603));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setLayout(null);

        btnguardarfoto.setText("Guardar foto");
        btnguardarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarfotoActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardarfoto);
        btnguardarfoto.setBounds(138, 11, 141, 41);

        btnverfoto.setText("Ver foto");
        btnverfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverfotoActionPerformed(evt);
            }
        });
        jPanel2.add(btnverfoto);
        btnverfoto.setBounds(377, 11, 138, 41);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 481, 790, 120);

        javax.swing.GroupLayout jpfotoLayout = new javax.swing.GroupLayout(jpfoto);
        jpfoto.setLayout(jpfotoLayout);
        jpfotoLayout.setHorizontalGroup(
            jpfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jpfotoLayout.setVerticalGroup(
            jpfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jPanel1.add(jpfoto);
        jpfoto.setBounds(90, 50, 598, 334);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarfotoActionPerformed
        guardarFoto(con);        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarfotoActionPerformed

    private void btnverfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverfotoActionPerformed
       new verfoto(this, true, verFoto(con)).setVisible(true); ;        // TODO add your handling code here:
    }//GEN-LAST:event_btnverfotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tomarfoto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tomarfoto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tomarfoto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tomarfoto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tomarfoto2 dialog = new tomarfoto2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardarfoto;
    private javax.swing.JButton btnverfoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JPanelWebCam.JPanelWebCam jpfoto;
    // End of variables declaration//GEN-END:variables
}
